itis_app/urls.py
from django.urls import path

from itis_app.views import index

app_name = 'itis_app'

urlpatterns = [
    path('', index, name='index'),
]

itis_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('itis_app.urls', namespace='itis_app')),
]

itis_app/models.py
from django.db import models


class AnalysisResult(models.Model):
    age = models.IntegerField(default=0)
    creatinine_phosphokinase = models.IntegerField(default=0)
    ejection_fraction = models.IntegerField(default=0)
    platelets = models.IntegerField(default=0)
    time = models.IntegerField(default=0)
    death_event = models.IntegerField(blank=True, default=0)
    create_timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Результаты анализов'

    def __str__(self):
        return str(self.death_event)

itis_app/forms.py
from django import forms

from itis_app.models import AnalysisResult

default_widget_class = 'form-control py-4'


class DataUploadForm(forms.Form):
    age = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': 'Возраст'}))
    creatinine_phosphokinase = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': 'Креатинфосфокиназа'}))
    ejection_fraction = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': 'Выброс фракций'}))
    platelets = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': 'Тромбоциты'}))
    time = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': 'Время'}))

    class Meta:
        model = AnalysisResult
        fields = ('age', 'creatinine_phosphokinase', 'ejection_fraction', 'platelets', 'time')

    def __init__(self, *args, **kwargs):
        super(DataUploadForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = default_widget_class

itis_app/views.py
from django.shortcuts import render
from django.contrib import messages

from itis_app.forms import DataUploadForm
from itis_app.core.start_check import start
from itis_app.models import AnalysisResult


def index(request):
    context = {
        'title': 'SSZ Site',
    }
    if request.method == 'POST':
        form = DataUploadForm(data=request.POST)
        if form.is_valid():
            print(request.POST)
            age = request.POST['age']
            cr_ph = request.POST['creatinine_phosphokinase']
            ej_fr = request.POST['ejection_fraction']
            platelets = request.POST['platelets']
            time = request.POST['time']

            death_event = start(age, cr_ph, ej_fr, platelets, time)

            result = AnalysisResult(age=age, creatinine_phosphokinase=cr_ph, ejection_fraction=ej_fr,
                                    platelets=platelets, time=time, death_event=death_event)
            result.save()

            context['result'] = bool(death_event)

        else:
            messages.info(request, 'Format Error: Form not valid!')

    else:
        form = DataUploadForm()

    context['form'] = form

    return render(request, 'itis_app/index.html', context)

itis_app/templates/itis_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'itis_app:index' %}"> SSZ Service </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>

<!-- Page Content -->
{% block content %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="https://kit.fontawesome.com/821a23fdd5.js" crossorigin="anonymous"></script>
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

itis_app/templates/itis_app/index.html
{% extends 'itis_app/base.html'%}
{% load static %}

{% block css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            {% if messages or form.errors %}
                <div class="alert
                    {% if messages %} {% if message.tags == info %}
                    alert-warning {% else %} alert-success {% endif %}
                    {% else %} alert-warning {% endif %}
                    alert-dismissible fade show" role="alert" style="margin-top: 50px;">
                    {% if messages %}
                        {% for message in messages%}
                            {{ message }}
                        {% endfor %}
                    {% else %}
                        {{ form.non_field_errors }}
                    {% endif %}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
            <div class="row">
                <div class="col-lg-7" style="margin-top: 50px; margin-left: 25px">
                    <h1 class="mt-6">Выявление сердечно-сосудистых заболеваний</h1>
                    <p>Сердечно-сосудистые заболевания (ССЗ) остаются основной причиной преждевременной смерти во всем мире. По данным эпидемиологических исследований, профилактика ССЗ высоко эффективна. Снижение смертности от ИБС на 50% связано с воздействием на факторы риска и только на 40% с улучшением лечения.
Данный сайт предназначен для выявления подверженности организма ССЗ. По таким признакам как возраст, креатинфосфокиназа, выброс фракции, тромбоциты и время будет выявлена группа риска пациента.</p>
                </div>
                <div class="col-lg-6" style="margin-top: 25px; margin-left: 25px">
                    <form action="{% url 'itis_app:index' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    {{ form.age }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    {{ form.creatinine_phosphokinase }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    {{ form.ejection_fraction }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    {{ form.platelets }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    {{ form.time }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 20px;">
                                <input class="btn btn-info btn-block" type="submit" value="Получить ответ">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-5" >
                {% if result %}
                    <div class="alert alert-danger" role="alert" style="margin-top: 25px; margin-left: 25px">
                        <h4 class="alert-heading" align="center">Вы в зоне риска!</h4>
                    </div>
                {% endif%}
            </div>
        </div>
    </section>
{% endblock %}